# .readthedocs.yaml

version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.9"

sphinx:
  configuration: docs/source/conf.py

python:
  version: "3.9"
  install:
    - requirements: docs/docs_require.txt
    - method: pip
      path: .
