var searchData=
[
  ['data_5fpreprocess_2epy',['data_preprocess.py',['../data__preprocess_8py.html',1,'']]],
  ['deconvolution_2epy',['deconvolution.py',['../deconvolution_8py.html',1,'']]],
  ['demo_5fcaiman_2epy',['demo_caiman.py',['../demo__caiman_8py.html',1,'']]],
  ['demo_5fcaiman_5fbasic_2epy',['demo_caiman_basic.py',['../demo__caiman__basic_8py.html',1,'']]],
  ['demo_5fcaiman_5fbenchmark_2epy',['demo_caiman_benchmark.py',['../demo__caiman__benchmark_8py.html',1,'']]],
  ['demo_5fcaiman_5fcnmf_2epy',['demo_caiman_cnmf.py',['../demo__caiman__cnmf_8py.html',1,'']]],
  ['demo_5fcaiman_5fcnmf_5fat_2epy',['demo_caiman_cnmf_AT.py',['../demo__caiman__cnmf___a_t_8py.html',1,'']]],
  ['demo_5fcaiman_5fcnmf_5fjan_2epy',['demo_caiman_cnmf_JAN.py',['../demo__caiman__cnmf___j_a_n_8py.html',1,'']]],
  ['demo_5fcaiman_5fcnmf_5fyi_2epy',['demo_caiman_cnmf_Yi.py',['../demo__caiman__cnmf___yi_8py.html',1,'']]],
  ['demo_5fcaiman_5fpatches_2epy',['demo_caiman_patches.py',['../demo__caiman__patches_8py.html',1,'']]],
  ['demo_5fcaiman_5fwip_2epy',['demo_caiman_wip.py',['../demo__caiman__wip_8py.html',1,'']]],
  ['demo_5fdan_2epy',['demo_dan.py',['../demo__dan_8py.html',1,'']]],
  ['demo_5felastic_5fand_5fonline_2epy',['demo_elastic_and_online.py',['../demo__elastic__and__online_8py.html',1,'']]],
  ['demo_5fmotion_5fcorrection_2epy',['demo_motion_correction.py',['../demo__motion__correction_8py.html',1,'']]],
  ['demo_5fpipeline_2epy',['demo_pipeline.py',['../demo__pipeline_8py.html',1,'(Global Namespace)'],['../demos__detailed_2demo__pipeline_8py.html',1,'(Global Namespace)']]],
  ['demo_5fpipeline_5flosonczy_2epy',['demo_pipeline_losonczy.py',['../demo__pipeline__losonczy_8py.html',1,'']]],
  ['demo_5fpipeline_5fnin_2epy',['demo_pipeline_NIN.py',['../demo__pipeline___n_i_n_8py.html',1,'']]],
  ['demo_5fpipeline_5fnin_5f2_2epy',['demo_pipeline_NIN_2.py',['../demo__pipeline___n_i_n__2_8py.html',1,'']]],
  ['demo_5fpipeline_5fnin_5fmultifile_2epy',['demo_pipeline_NIN_multifile.py',['../demo__pipeline___n_i_n__multifile_8py.html',1,'']]],
  ['demo_5fpipeline_5fzebra_2epy',['demo_pipeline_Zebra.py',['../demo__pipeline___zebra_8py.html',1,'']]],
  ['demo_5fslurm_2epy',['demo_slurm.py',['../demo__slurm_8py.html',1,'']]],
  ['demo_5ftest_5fautocomp_2epy',['demo_test_autocomp.py',['../demo__test__autocomp_8py.html',1,'']]],
  ['demomotioncorrectionparallel_2epy',['DemoMotionCorrectionParallel.py',['../_demo_motion_correction_parallel_8py.html',1,'']]]
];
